import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import m2cgen as m2c
import os

# Dynamic paths so it runs from anywhere
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_FILE = os.path.join(BASE_DIR, "../data/raw_probes.csv")
GO_OUTPUT_FILE = os.path.join(BASE_DIR, "../engine/rf_model.go")

def train_and_export_model():
    print(f"[*] Loading dataset from {DATA_FILE}...")
    
    # 1. Load Data
    try:
        df = pd.read_csv(DATA_FILE)
    except FileNotFoundError:
        print("[!] Error: raw_probes.csv not found. Run scanner.py first.")
        return

    # 2. Define Features and Target (MATCHING THE SCANNER EXACTLY)
    # These are the exact column names generated by your scanner.py
    X = df[['is_global_tld', 'is_id_tld', 'subdomain_depth', 'hour']]
    y = df['optimal_class']

    print(f"[*] Training Random Forest (Committee of Experts) on {len(df)} samples...")

    # 3. Train the Random Forest
    # n_estimators=15 is small enough for fast Go execution but accurate enough for an ensemble
    clf = RandomForestClassifier(n_estimators=15, max_depth=10, random_state=42)
    clf.fit(X, y)

    print("[*] Model trained successfully! Exporting native Go code...")

    # 4. Export to Native Go Code (m2cgen)
    go_code = m2c.export_to_go(clf)
    
    # Add the package declaration required by Go
    if not go_code.startswith("package main"):
        go_code = "package main\n\n" + go_code
    
    with open(GO_OUTPUT_FILE, 'w') as f:
        f.write(go_code)
    
    print(f"[*] SUCCESS! Random Forest exported to {GO_OUTPUT_FILE}")

if __name__ == "__main__":
    train_and_export_model()
