package main

// The function 'score' is automatically generated by m2cgen from trainer.py
// It will take your feature array []float64 and return the prediction.

func PredictBestResolver(hopCount float64, timeOfDay float64, isGlobalTLD float64, subDepth float64) string {
	
	// Create the feature array expected by the generated Random Forest
	features := []float64{hopCount, timeOfDay, isGlobalTLD, subDepth}
	
	// Call the generated Random Forest logic
	predictionArray := score(features)
	
	// The array returns confidence scores for each class (ISP, Cloudflare, Google, Quad9)
	// Find the index with the highest score
	bestIndex := 0
	maxScore := predictionArray[0]
	for i, s := range predictionArray {
		if s > maxScore {
			maxScore = s
			bestIndex = i
		}
	}

	// Map index back to resolver
	resolvers := []string{"ISP", "Cloudflare", "Google", "Quad9"}
	return resolvers[bestIndex]
}